[project]
name = "pve-drop-guest-caches"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "darkhaniop", email = "72267237+darkhaniop@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "hypercorn>=0.17.3",
]

[build-system]
requires = ["uv_build>=0.8.8,<0.9.0"]
build-backend = "uv_build"
