[project]
name = "pve-multiexec"
version = "0.1.0"
description = "A simple utility that provides a RESTful API for batch execting commands in Proxmox VE quest VMs with `qemu-quest-agent`"
readme = "README.md"
authors = [
    { name = "darkhaniop", email = "72267237+darkhaniop@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "cachetools>=6.1.0",
    "fastapi>=0.116.1",
    "hypercorn>=0.17.3",
    "proxmoxer>=2.2.0",
    "pydantic-settings>=2.12.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
    "sqlmodel>=0.0.24",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]

[build-system]
requires = ["uv_build>=0.8.8,<0.9.0"]
build-backend = "uv_build"

